//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cursant
    {
        public Cursant()
        {
            this.Tests = new HashSet<Test>();
        }
    
        public int IdCursant { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Hint { get; set; }
    
        public virtual ICollection<Test> Tests { get; set; }
    }
}
