//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domeniu
    {
        public Domeniu()
        {
            this.Intrebares = new HashSet<Intrebare>();
            this.Subdomenius = new HashSet<Subdomeniu>();
        }
    
        public int IdDomeniu { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
    
        public virtual ICollection<Intrebare> Intrebares { get; set; }
        public virtual ICollection<Subdomeniu> Subdomenius { get; set; }
    }
}
