//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Intrebare
    {
        public Intrebare()
        {
            this.VariantaRaspuns = new HashSet<VariantaRaspun>();
            this.RaspunsCursants = new HashSet<RaspunsCursant>();
        }
    
        public int IdIntrebare { get; set; }
        public Nullable<int> IdDomeniu { get; set; }
        public Nullable<int> IdSubdomeniu { get; set; }
        public string Text { get; set; }
        public int Tip { get; set; }
    
        public virtual Domeniu Domeniu { get; set; }
        public virtual Subdomeniu Subdomeniu { get; set; }
        public virtual ICollection<VariantaRaspun> VariantaRaspuns { get; set; }
        public virtual ICollection<RaspunsCursant> RaspunsCursants { get; set; }
    }
}
