//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaspunsCursant
    {
        public int Id { get; set; }
        public int IdTest { get; set; }
        public int IdIntrebare { get; set; }
        public int IdRaspuns { get; set; }
    
        public virtual Intrebare Intrebare { get; set; }
        public virtual Test Test { get; set; }
        public virtual VariantaRaspun VariantaRaspun { get; set; }
    }
}
