//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subdomeniu
    {
        public Subdomeniu()
        {
            this.Intrebares = new HashSet<Intrebare>();
        }
    
        public int IdSubdomeniu { get; set; }
        public Nullable<int> IdDomeniu { get; set; }
        public string Nume { get; set; }
        public string Descriere { get; set; }
    
        public virtual Domeniu Domeniu { get; set; }
        public virtual ICollection<Intrebare> Intrebares { get; set; }
    }
}
