//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TesteEntities : DbContext
    {
        public TesteEntities()
            : base("name=TesteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cursant> Cursants { get; set; }
        public DbSet<Domeniu> Domenius { get; set; }
        public DbSet<Intrebare> Intrebares { get; set; }
        public DbSet<RaspunsCursant> RaspunsCursants { get; set; }
        public DbSet<Subdomeniu> Subdomenius { get; set; }
        public DbSet<Test> Tests { get; set; }
        public DbSet<VariantaRaspun> VariantaRaspuns { get; set; }
    }
}
