//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tema3Sem2.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantaRaspun
    {
        public VariantaRaspun()
        {
            this.RaspunsCursants = new HashSet<RaspunsCursant>();
        }
    
        public int IdRaspuns { get; set; }
        public Nullable<int> IdIntrebare { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Corect { get; set; }
        public string Motivatie { get; set; }
    
        public virtual Intrebare Intrebare { get; set; }
        public virtual ICollection<RaspunsCursant> RaspunsCursants { get; set; }
    }
}
